.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2015 Darrick J. Wong <djwong@unknown>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH FILEMAPPER 1 "April 22, 2015"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
xfsmapper \- Analyze an XFS image for use with filemapper
.SH SYNOPSIS
.B filemapper
.I dbfile
.I fs_device
.SH DESCRIPTION
This manual page documents briefly the
.B xfsmapper
and
.B bar
commands.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBxfsmapper\fP analyzes the internals of an XFS filesystem and
generates a snapshot that the filemapper program can use to visualize
and query the physical layout of the filesystem.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.I dbfile
Store the filesystem analysis in this file.
.TP
.I fs_device
Open this raw device for analysis.
.TP
.B \-h, \-\-help
Show summary of options.
.SH SEE ALSO
.BR filemapper (1).
.br
